### ISSUE TITLE
Web application version?

### ISSUE THREAD

**Issue by ghost** [etsy/divertsy-client#3]
Consider releasing a version that runs completely server side and allows users to manually enter weighed amounts via a web form. You can close this issue after reading.

**Comment by b3nn** [comment]
Hi. Thanks for the feedback. We are considering that for release later this year. That should be the "divertsy-sever" which allows manual entries as well as report generation using the data collected from the clients. 

Right now, there is a feature in the Android app so you can manual input values if you don't have a scale or there's issues with the USB connection. Just double tap the "0.0" on screen, enter the value, the press the waste stream button. Data gets recorded normally. I'll have the wiki updated soon with some screen shots.
